#!/bin/sh

# This script is meant to be used with [FSGI][1].  It's a request handler for
# an HTTP server that produces SVG images of temperature/humidity measurements
# over a specified interval.
#
# [1]: https://github.com/dgoffredo/fsgi

dir=$(dirname "$0")

first=0001-01-01
if [ -e request/query/first/0 ]; then
  # escape single quotes for SQL
  first=$(<request/query/first/0 tr "'" "''")
fi

last=9999-12-31
if [ -e request/query/last/0 ]; then
  # escape single quotes for SQL
  last=$(<request/query/last/0 tr "'" "''")
fi

/usr/local/bin/sqlite3 "$dir/db.sqlite" <<END_SQL
.headers off
.mode columns
.output dump.txt
select when_iso, temperature_celsius, humidity_percent
from reading
where date(when_iso) between '$first' and '$last'
order by when_iso;
END_SQL

printf 'image/svg+xml' >response/headers/Content-Type

>response/body gnuplot <<'END_GNUPLOT'
set xdata time
set timefmt '%Y-%m-%dT%H:%M:%SZ'

set y2tics

set xlabel 'Time (UTC)' offset 0,-1
set ylabel 'Temperature (°C)'
set y2label 'Relative Humidity (%)'

set title 'Temperature and Relative Humidity versus Time'

set terminal svg size 1024,769 fixed enhanced font 'Arial,12' butt dashlength 1.0

plot 'dump.txt' using 1:2 title 'Temperature (°C) [left axis]' axes x1y1, \
     'dump.txt' using 1:3 title 'Relative Humidity (%) [right axis]' axes x1y2
END_GNUPLOT

